# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _

SALARY_CHOICES = [
	('all', ('Tous')),
	('0', ('')),
	('1', 'SMIC'),
	('2', '18k'),
	('3', '20k'),
	('4', '22k'),
	('5', '24k'),
	('6', '26k'),
	('7', '28k'),
	('8', '30k'),
	('9', '32k'),
	('10', '34k'),
	('11', '36k'),
	('12', '38k'),
	('13', '40k'),
	('14', '42k'),
	('15', '44k'),
	('16', '46k'),
	('17', '48k'),
 	('18', '50k et plus')
]

OFFER_CHOICES = [
	('all', _(u'Tous')),
	('0', (u'')),
	('8', _(u'Alternance')),
	('3', _(u'Auto entrepreneur')),
	('4', _(u'CDD')),
	('5', _(u'CDI')),
	('1', _(u'Freelance')),
	('7', _(u'Intérim')),
	('2', _(u'Indépendant')),
	('6', _(u'Stage')),
	('9', _(u'Stage et emploi'))
]

CATEGORY_CHOICES = [
	('all', u'Tous'),
	('0', (u'')),
	('19', u'Agriculture'),
	('20', u'Agroalimentaire'), 
	('34', u'Animation'), 
	('21', u'Artisanat'),
	('1',  u'Assurance'),
	('28', u'Audiovisuel'),
	('12', u'Batiment et Travaux publics'), 
	('2',  u'Banque'),
	('31', u'Biotechnologies'), 
	('3',  u'Comptabilite'), 
	('9',  u'Communication'),
	('29', u'Culture'), 
	('10', u'Distribution'),
	('35', u'Education'),
	('17', u'Energie et nucleaire'), 
	('22', u'Energies renouvelables'),
	('23', u'Environnement'),
	('4',  u'Finance'), 
	('36', u'Humanitaire'), 
	('37', u'Hotellerie'),
	('13', u'Immobilier'), 
	('18', u'Industrie'), 
	('5',  u'Informatique'), 
	('40', u'International'),
	('7',  u'Juridique'), 
	('25', u'Luxe'), 
	('14', u'Logistique'), 
	('11', u'Marketing'),
	('26', u'Mode'), 
	('38', u'Nettoyage'), 
	('27', u'Production'),
	('24', u'Recherche et Developpement'),
	('8',  u'Ressources Humaines'), 
	('39', u'Restauration'), 
	('32', u'Sante'),
	('33', u'Social'), 
	('15', u'Securite'), 
	('6',  u'Telecom'), 
	('16', u'Transport'),
	('30', u'Tourisme'), 
	('41', u'Travailleur Handicape')
	
]


REGION_CHOICES = [ 
	('all', _(u'Tous')),
	('0', 	(u'')),	
	('8', 	_(u'Alsace')), 
	('13', 	_(u'Aquitaine')), 
	('21', 	_(u'Auvergne')),
	('4', 	_(u'Basse Normandie')), 
	('11', 	_(u'Bourgogne')), 
	('6', 	_(u'Bretagne')), 
	('7', 	_(u'Champagne Ardenne')), 
	('15', 	_(u'Corse')), 
	('10', 	_(u'Centre')), 
	('5', 	_(u'Ile de France')), 
	('22', 	_(u'Franche Comte')),
	('3', 	_(u'Haute Normandie')), 
	('17', 	_(u'Languedoc Roussillon')), 
	('20', 	_(u'Limousin')),
	('18', 	_(u'Lorraine')),
	('16', 	_(u'Midi Pyrenees')), 
	('1', 	_(u'Nord Pas de Calais')), 
	('2', 	_(u'Picardie')), 
	('14', 	_(u'PACA')), 
	('9', 	_(u'Pays de la Loire')), 
	('12', 	_(u'Rhone Alpes')), 
	('19', 	_(u'Poitou Charentes'))
]


YESNO = [
	
	('all', _(u'Tous')),
    ('Yes', _(u'Yes')),
    ('No',  _(u'No'))
]


DEPARTEMENT_CHOICES = [
	('all', _('Tous')),
	('0', ('')),
	('1', u' Ain'),
	('2', u' Aisne'),
	('3', u' Allier'),
	('4', u' Alpes de Hautes-Provence'),
	('5', u' Hautes-Alpes'),
	('6', u' Alpes-Maritimes'),
	('7', u' Ardeche'),
	('8', u' Ardennes'),
	('9', u' Ariege'),
	 ('10', u' Aube'),
	('11', u' Aude'),
	('12', u' Aveyron'),
	('13', u' Bouches-du-Rhone'),
	('14', u' Calvados'),
	('15', u' Cantal'),
	('16', u' Charente'),
	('17', u' Charente-Maritime'),
	('18', u' Cher'),
	('20', u' Correze'),
	('21', u' Cote-d\'Or'),
	('22', u' Cotes d\'Armor'),
	('23', u' Creuse'),
	('24', u' Dordogne'),
	('25', u' Doubs'),
	('26', u' Drome'),
	('27', u' Eure'),
	('28', u' Eure-et-Loir'),
	('29', u' Finistere'),
	('30', u' Gard'),
	('31', u' Haute-Garonne'),
	('32', u' Gers'),
	('33', u' Gironde'),
	('34', u' Herault'),
	('35', u' Ille-et-Vilaine'),
	('36', u' Indre'),
	('37', u' Indre-et-Loire'),
	('38', u' Isere'),
	('39', u' Jura'),
	('40', u' Landes'),
	('41', u' Loir-et-Cher'),
	('42', u' Loire'),
	('43', u' Haute-Loire'),
	('44', u' Loire-Atlantique'),
	('45', u' Loiret'),
	('46', u' Lot'),
	('47', u' Lot-et-Garonne'),
	('48', u' Lozere'),
	('49', u' Maine-et-Loire'),
	('50', u' Manche'),
	('51', u' Marne'),
	('52', u' Haute-Marne'),
	('53', u' Mayenne'),
	('54', u' Meurthe-et-Moselle'),
	('55', u' Meuse'),
	('56', u' Morbihan'),
	('57', u' Moselle'),
	('58', u' Nievre'),
	('59', u' Nord'),
	('60', u' Oise'),
	('61', u' Orne'),
	('62', u' Pas-de-Calais'),
	('63', u' Puy-de-Dome'),
	('64', u' Pyrenees-Atlantiques'),
	('65', u' Hautes-Pyrenees'),
	('66', u' Pyrenees-Orientales'),
	('67', u' Bas-Rhin'),
	('68', u' Haut-Rhin'),
	('69', u' Rhone'),
	('70', u' Haute-Saone'),
	('71', u' Saone-et-Loire'),
	('72', u' Sarthe'),
	('73', u' Savoie'),
	('74', u' Haute-Savoie'),
	('75', u' Paris'),
	('76', u' Seine-Maritime'),
	('77', u' Seine et Marne'),
	('78', u' Yvelines'),
	('79', u' Deux-Sevres'),
	('80', u' Somme'),
	('81', u' Tarn'),
	('82', u' Tarn-et-Garonne'),
	('83', u' Var'),
	('84', u' Vaucluse'),
	('85', u' Vendee'),
	('86', u' Vienne'),
	('87', u' Haute-Vienne'),
	('88', u' Vosges'),
	('89', u' Yonne'),
	('90', u' Territoire-de-Belfort'),
	('91', u' Essonne'),
	('92', u' Hauts de Seine'),
	('93', u' Seine Saint Denis'),
	('94', u' Val de Marne'),
	('95',  "Val d\'Oise"),
	('96', u' Corse-du-Sud'),
	('97', u' Haute-Corse')
]

DISPONIBILITY_CHOICES = [
	('all', _('Tous')),
	('0', ('')),
	('1', 'immediat'),
	('2', '1 mois'),
	('3', '2 mois'),
	('4', '3 mois'),
	('5', '3 mois et plus ')
]

STATUS_CHOICES = [
	('all', _('Tous')),
	('0', ('')),
	('1', 'en poste'),
	('2', 'preavis en cous ou termine')
]

STUDY_LEVEL_CHOICES = [
	('all', _('Tous')),
	('0', ('')),
	('1', '2nd'),
	('2', 'BAC'),
	('3', 'BAC+2'), 
	('4', 'BAC+3'), 
	('5', 'BAC+4'),
	('6', 'BAC+5 et plus'),
	('7', 'BEPC'),
	('8', 'CAP/BEF')
]

EXPERIENCE_CHOICES = [
	('all', _('Tous')),
	('0', ('')),
	('1', 'debutant'),
	('2', '6 mois'),
	('3', '1 ans '),
	('4', '2 ans '),
	('5', '3 ans '),
	('6', '4 ans '),
	('7', '5 a 10 ans '),
	('8', '10 ans et plus')
]

PERIOD_CHOICES = [
	('all', _('Tous')),
	('0', ('')),
	('1', 'temps plein'),
	('2', 'temps partiel')
]

